name: til_summary

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16.7.0
      - name: Install dependencies
        run: yarn install
      - name: Compile the til summary
        run: node ./index.js compile
      - name: Update README.md
        run: |
          git config --global user.email "hungthai1401.it@gmail.com"
          git config --global user.name "Thai Nguyen Hung"
          git add .
          git commit -m "Updated README.md" || echo "No changes to commit"
          git push
